### ISSUE TITLE
fix edit message feature!!!

### ISSUE THREAD

**Issue by cryolune** [The-Virtual-Dancers/Virtual_Dancers_Messenger#4]
Fix the edit button so that no one will be able to edit messages shared by other members.

**Comment by Cirediallo** [comment]
Hello can you more elaborate ? when I run your app I just see you can write and add a message which you can delete or modify. So is there any login form to check who send a message ? the only user I see is Virtual Dancers. Do you want to add that functionnality ? because I this point I see none of it

**Comment by cryolune** [comment]
Helle @Cirediallo as of now anyone can add, edit, delete the same messages. The only feature we need right now is a "Name Field" before sending a message also we need to fix the edit and delete button so that the User1 won't have access to delete or edit messages from User2.

**Comment by richardjob** [comment]
Working on this.

**Comment by Cirediallo** [comment]
ok go ahead @richardjob
